apiVersion: v1
kind: Pod
metadata:
  name: branch-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-wan
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sleep", "3650d"]
    securityContext:
      privileged: true
