apiVersion: v1
kind: Pod
metadata:
  name: phase1-service-a
  annotations:
    k8s.v1.cni.cncf.io/networks: phase1-dp-lan
spec:
  nodeName: aks-nodepool1-38799324-vmss000001
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/bash", "-lc", "sleep infinity"]
    securityContext:
      privileged: true