apiVersion: v1
kind: Pod
metadata:
  name: vpp-mana
spec:
  hostNetwork: true
  hostPID: true
  nodeName: aks-nodepool1-38799324-vmss000000
  containers:
  - name: vpp
    image: ubuntu:22.04
    command: ["/bin/bash", "-c", "ulimit -l unlimited && exec sleep infinity"]
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "4Gi"
      limits:
        memory: "8Gi"
    volumeMounts:
    - name: hugepages
      mountPath: /dev/hugepages
    - name: sys
      mountPath: /sys
    - name: dev
      mountPath: /dev
    - name: host-root
      mountPath: /host
    - name: run
      mountPath: /run
  volumes:
  - name: hugepages
    hostPath:
      path: /dev/hugepages
      type: DirectoryOrCreate
  - name: sys
    hostPath:
      path: /sys
  - name: dev
    hostPath:
      path: /dev
  - name: host-root
    hostPath:
      path: /
  - name: run
    emptyDir: {}
