apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: client
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-lan
spec:
  nodeName: aks-dpdkpool-11331723-vmss000000
  containers:
  - name: client
    image: ubuntu:22.04
    command: ["/bin/sleep", "3650d"]
    securityContext:
      privileged: true
