apiVersion: v1
kind: Pod
metadata:
  name: debug-hugepool
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-hugepool-28158901-vmss000000
  containers:
  - name: debug
    image: ubuntu:22.04
    command: ["/bin/sleep", "infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: sys
      mountPath: /sys
    - name: dev
      mountPath: /dev
  volumes:
  - name: sys
    hostPath:
      path: /sys
  - name: dev
    hostPath:
      path: /dev
